name: python and node install build start workflow


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Test clear_channel_context.py
      run: |
        python3 -m unittest ./python_test/test_clear.py
    - name: Test ask.py
      run: |
        python3 -m unittest ./python_test/test_ask.py
