name: python and node install build start workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Set up Node 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r pip_requirements.txt 
    - name: Install node dependencies
      run: |
        npm install
    - name: Build npm
      run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Make test articles
      run: |
        python3 process_test_articles.py
    - name: Test ask.py
      run: |
        python3 -m unittest ./python_test/test_ask.py
